### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by munen** [nbulaj/ruby-chromedriver#1]
Hi nbulaj

First of all, thanks for creating this Docker image. We have been using it to run our Rails tests on Gitlab and we are thankful for that!

There's one tip that I would like to pass along. In the commit that you [just did](https://github.com/nbulaj/ruby-chromedriver/commit/cd749668726610c0befdc9447343e285a2500f07), you have undone all the good that you created before. Don't get me wrong, this is not meant as an insult - it's more of a technical nature(;

You have created Docker images and have versioned them. This is idiomatic practice and ensures that people (you, us) can built systems that rely on containers that never change. This simplifies life a whole lot.

In your last commit, you have changed something in the last and I presume you have rebuilt the Docker containers and pushed them to Dockerhub. By doing that, you now have new versions (not only of Ruby what you intended), but also of Chrome and Chromedriver and everything else that you manually installed on those containers.

You could have done that for a new version of the image. It's not idiomatic practice to change it in an existing container version, because inherently the container will change.

For us, your new and old images don't work anymore and the tests crash.

I hope the image still works for your original intent, so that at least you can continue working with your image(;

All the best
Alain

**Comment by nbulaj** [comment]
Hi @munen .

I can't see anything wrong in changing old images because it's a common practice: you can check [postgres docker history](https://github.com/docker-library/postgres/commits/master/10) or any other Docker image and [it's tags](https://hub.docker.com/r/library/postgres/tags/). People that already uses this images will need to update them (just pull the image). This changes can be connected with fixing some dependencies, vulnerabilities, reducing image size and many other useful things.

If image was modified, docker will pull the new version (as for my GitLab CI - `Pulling docker image nbulai/ruby-chromedriver:2.33 ...`) and there are no problems. Or I don't understand what best practices you are talking about :)

What about your problem (and my :) ) - there is a problem with the latest [Selenium driver and Chromedriver](https://github.com/SeleniumHQ/selenium/issues/4961) and it fixes by adding [`--no-sandbox`](https://github.com/SeleniumHQ/selenium/issues/4961#issuecomment-346821657) option to `chromeOptions`

```ruby
chromeOptions: { args: %w[headless disable-gpu no-sandbox] }
```
And everything will work.  The bug was reported in the Chromedriver Google user group.

**Comment by nbulaj** [comment]
Although ... The idea of not touching existing layers (especially software versions) is very logical. In any case, thanks for informing about the problem!

I reverted old images so you can use them again, but `latest` tag is related to a new one (2.33) with the latest _Chromedriver_ and _Google Chrome_ (so you will probably need to use `--no-sandbox` option for your Capybara driver before bug will be fixed).

**Comment by munen** [comment]
I am not aware of the practice as you describe it. And the links that you give show no indication for it. The PG tags clearly show that the older the tag is (in revision numbers), the longer the 'last updated at' timestamp is.

On the other hand I am perfectly aware that there is an issue with the current chrome build. That is exactly why using an immutable container is great - so that the world doesn't change from under you. If you change an old Docker image tag and CI pulls this changed version, you run into the same 'world change' issues as without a Docker image. You could just have as easily a 'apt-get install chromedriver' in your CI build tool.

However, I am not here to argue, just wanted to share what I have come to understand as best practice. You're the maintainer of the image and you are perfectly within your rights to have a different opinion(;  

I do appreciate the tip with `--no-sandbox`. Thank you for sharing!

**Comment by nbulaj** [comment]
@munen if you will check PG tags, than you can see that the oldest version of the database (`9.3`) was [updated just 23 days ago](https://store.docker.com/images/postgres/plans/cfa7881b-dad1-4d72-8dca-58b5d15bfc71?tab=tags) (but it was first created and pushed 16 Jul 2014) or even `9.3-alpine` (Last update: 4 days ago).

Anyway, as I said - I thought a little and agree with you. It must be immutable in most of cases (but not security, for example, as it is very important - maybe not for tests, but for real systems and so on). So I rolled back the old images and now it must be OK.

Big thanks to you for this tip and report! :+1:
